// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sysd_obj.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Obj struct {
	// name of the obj
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// string of json format
	Val                  string               `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Obj) Reset()         { *m = Obj{} }
func (m *Obj) String() string { return proto.CompactTextString(m) }
func (*Obj) ProtoMessage()    {}
func (*Obj) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e1472cd4b8bc1c, []int{0}
}

func (m *Obj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Obj.Unmarshal(m, b)
}
func (m *Obj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Obj.Marshal(b, m, deterministic)
}
func (m *Obj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Obj.Merge(m, src)
}
func (m *Obj) XXX_Size() int {
	return xxx_messageInfo_Obj.Size(m)
}
func (m *Obj) XXX_DiscardUnknown() {
	xxx_messageInfo_Obj.DiscardUnknown(m)
}

var xxx_messageInfo_Obj proto.InternalMessageInfo

func (m *Obj) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Obj) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

func (m *Obj) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func init() {
	proto.RegisterType((*Obj)(nil), "main.Obj")
}

func init() { proto.RegisterFile("sysd_obj.proto", fileDescriptor_b6e1472cd4b8bc1c) }

var fileDescriptor_b6e1472cd4b8bc1c = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xae, 0x2c, 0x4e,
	0x89, 0xcf, 0x4f, 0xca, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc,
	0x93, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x25, 0x95, 0xa6, 0xe9, 0x97,
	0x64, 0xe6, 0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16, 0x40, 0x94, 0x29, 0x65, 0x71, 0x31, 0xfb, 0x27,
	0x65, 0x09, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0x81, 0xd9, 0x42, 0x02, 0x5c, 0xcc, 0x65, 0x89, 0x39, 0x12, 0x4c, 0x60, 0x21, 0x10, 0x53, 0xc8,
	0x96, 0x8b, 0x27, 0x27, 0xb1, 0xb8, 0x24, 0xbe, 0xb4, 0x20, 0x25, 0xb1, 0x24, 0x35, 0x45, 0x82,
	0x55, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x4a, 0x0f, 0x62, 0x89, 0x1e, 0xcc, 0x12, 0xbd, 0x10, 0x98,
	0x25, 0x41, 0xdc, 0x20, 0xf5, 0xa1, 0x10, 0xe5, 0x49, 0x6c, 0x60, 0x05, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xed, 0x20, 0x7f, 0xda, 0xab, 0x00, 0x00, 0x00,
}
